### ISSUE TITLE
Having non-text content in clipboard disables context menu

### ISSUE THREAD

**Issue by nikdiklic** [corpnewt/ProperTree#10]
I discovered this accidentally. I had an image on my clipboard, and every time I right-clicked, this happened: 
![image](https://user-images.githubusercontent.com/14840458/71294849-0ed45480-237a-11ea-9553-fa46ec80f6d9.png)

**Comment by corpnewt** [comment]
Thanks for the heads up. I'll push a fix for this soon.

-CorpNewt

**Comment by corpnewt** [comment]
Should be fixed with [this commit](https://github.com/corpnewt/ProperTree/commit/4a45ef12d7b87b79a80f97975a5da9982f64dfcc).

-CorpNewt
