### ISSUE TITLE
ProperTree comes out of focus after performing a snapshot

### ISSUE THREAD

**Issue by alyxferrari** [corpnewt/ProperTree#100]
Not sure if this happens on macOS and Linux too, but on Windows 11 (happened on Windows 10 too as I recall) whenever I perform a snapshot or clean snapshot, the ProperTree window comes out of focus and I have to click on it again to bring it back in focus.

This is a pretty minor bug, should hopefully be an easy fix. While I have your attention, thanks for making these great tools for free, I really appreciate it :)

**Comment by alyxferrari** [comment]
Update: This happens on macOS Monterey beta 6 too.

**Comment by corpnewt** [comment]
Hey there - should be fixed with [this commit](https://github.com/corpnewt/ProperTree/commit/c3e8f46b4f4129f3f42c1db6989d3d4159bfafe4).

-CorpNewt
