### ISSUE TITLE
Updated the Drivers structures in Opencore 0.7.3

### ISSUE THREAD

**Issue by qiutuleng** [corpnewt/ProperTree#103]
Hi
Opencore updated 0.7.3 yesterday, it's updated the Drivers structures,  automatically generated structures are no longer compatible the opencore version. and make the opencore startup failed.

old version:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Drivers</key>
	<array>
		<string>OpenCanopy.efi</string>
		<string>OpenRuntime.efi</string>
	</array>
</dict>
</plist>
```

new version:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Drivers</key>
	<array>
		<dict>
			<key>Path</key>
			<string>OpenRuntime.efi</string>
			<key>Enabled</key>
			<true/>
			<key>Arguments</key>
			<string></string>
		</dict>
		<dict>
			<key>Path</key>
			<string>OpenCanopy.efi</string>
			<key>Enabled</key>
			<true/>
			<key>Arguments</key>
			<string></string>
		</dict>
	</array>
</dict>
</plist>
```

This is a very good software, it's helps me a lot, thank you for your contributions.

Hope you have a good day.

**Comment by corpnewt** [comment]
It's updated for 0.7.3's Driver changes in [this commit](https://github.com/corpnewt/ProperTree/commit/38a0504816294a836b7cdb50a8edc238ec1a03fb).  Please let me know if you run into any issues - but I'll close this issue for the time being, thanks!

-CorpNewt
