### ISSUE TITLE
OC Clean Snapshot is messing up the Kernel section of config.plist file.

### ISSUE THREAD

**Issue by tecnicasopr** [corpnewt/ProperTree#107]
Kernel section tree gets mess-up after clean snapshot when using the latest commit a0db99cb9e8b691ed78f56e8d3c004f89a179266

**Comment by corpnewt** [comment]
Hey there - I still don't see any issues?

**Comment by Bhavinjain260** [comment]
Shouldn't be lilu the first kext in the order?
