### ISSUE TITLE
The open file operation failed to connect to the open and save panel service.

### ISSUE THREAD

**Issue by matteodev8** [corpnewt/ProperTree#111]
I got an issue in macOS Monterey 12.0.1 and ProperTree, if I want to load/save a file via the title bar, I get this strange error message.

![Error Message](https://user-images.githubusercontent.com/59450459/139383837-23e1ead5-609f-463a-a53a-93af781d67bd.png)

After I click OK, this comes up: "[Errno 2] No such file or directory: '/None'"

![grafik](https://user-images.githubusercontent.com/59450459/139383975-6c26db09-108a-4956-836a-444cee9d2fe0.png)

Python version: Python 3.10.0

**Comment by ttruong21** [comment]
@corpnewt 
I still got this error when using `/usr/local/bin/python3 3.9.7 - tk 8.6`

**Comment by corpnewt** [comment]
@ttruong21 the universal or intel release?  The universal release will have the issue as well (as mentioned in the FAQ).

-CorpNewt

**Comment by fjelgar** [comment]
Same problem, stuck with either the black screen problem or this error after trying all multiple versions of python. on macOS 12.0.1

**Comment by akavkl** [comment]
addition popup for me on 12.0.1
[Errno 2] No such file or directory: '/Users/{username}/None'

**Comment by akavkl** [comment]
temp solution for now is to install intel version from [miniconda](https://docs.conda.io/en/latest/miniconda.html) website

**Comment by arianmalmir** [comment]
that's right !

**Comment by matteodev8** [comment]
ig I will close this issue.
