### ISSUE TITLE
(Bug) OC snapshot DOES NOT work in the current version of Propertree

### ISSUE THREAD

**Issue by Overc1ocker** [corpnewt/ProperTree#118]
Please Fix. Here is the issue for reference.

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/macuser/Documents/tools/ProperTree/ProperTree.command", line 517, in oc_snapshot
    window.oc_snapshot(event,clean)
  File "/Users/macuser/Documents/tools/ProperTree/Scripts/plistwindow.py", line 1051, in oc_snapshot
    if efi.lower() in [x.lower() for x in add]:
  File "/Users/macuser/Documents/tools/ProperTree/Scripts/plistwindow.py", line 1051, in <listcomp>
    if efi.lower() in [x.lower() for x in add]:
AttributeError: 'collections.OrderedDict' object has no attribute 'lower'
`

**Comment by Overc1ocker** [comment]
This only occurs when loading config.plist before doing the snapshot. Not snapshotting after opening "blank" document

**Comment by corpnewt** [comment]
Can you also upload your config.plist?

**Comment by corpnewt** [comment]
Hmm - in looking at the code for the `plistwindow.py` module - that line does not even exist anymore.  Are you sure you're running the latest code?

In fact - [this commit](https://github.com/corpnewt/ProperTree/commit/b2bfde3067f7a717e994c49a55930a2ffb2e6acf#diff-75e362cab95b8e9e9af990afb57b2cd2ecf1e184f85d009fd986679474790691) (from March of last year) is the last one `plistwindow.py` had where that line exists *and* is at `line 1051` per your error - so it does appear that you are running an outdated version.  As of [this commit](https://github.com/corpnewt/ProperTree/commit/38a0504816294a836b7cdb50a8edc238ec1a03fb#diff-75e362cab95b8e9e9af990afb57b2cd2ecf1e184f85d009fd986679474790691) in September of last year, ProperTree has had support for the differing types of UEFI -> Driver entries in OC 0.7.3+

Please update and test again.

-CorpNewt

**Comment by Overc1ocker** [comment]
Sorry for bothering you. It turns out I had updated Propertree on one of my hackintoshes and not the other. Consider this closed.

Have a nice evening :)
