### ISSUE TITLE
Copy not working

### ISSUE THREAD

**Issue by Apethesis** [corpnewt/ProperTree#128]
Commit 638185f19d38e8854481eafec11f0529a595ab36, aka "Workaroud for tkinter not saving clipboard" broke it for me.
Can't copy keys n stuff.

**Comment by corpnewt** [comment]
Hey there - what's your environment (OS/python version, etc)?  Also - what exactly are you copying?  I'll test locally and see if I can recreate it.

I tested the commit on Windows 10 with python 3.10, and macOS on python 2.7 and 3.10 and it worked here.

-CorpNewt

**Comment by corpnewt** [comment]
Also worth asking if you have the `clip` (should you be running Windows) or `pbcopy` (if you're on macOS/Linux) binaries.  If not - I could wrap the copy check in a `try... except` block for that portion - and have it fall back on the regular tkinter clipboard functions if it fails.  I might do that while I'm waiting for a reply - as it won't hurt anything regardless.

-CorpNewt

**Comment by corpnewt** [comment]
I pushed a test commit [here](https://github.com/corpnewt/ProperTree/commit/31fb61177193222d154c9a92ed37f8540af5b930) - which may fix the issue (as I'm just guessing your system lacks `clip` or `pbcopy`).  This will restore the prior behavior should neither of those binaries exist.

-CorpNewt

**Comment by Apethesis** [comment]
> Hey there - what's your environment (OS/python version, etc)? Also - what exactly are you copying? I'll test locally and see if I can recreate it.
> 
> I tested the commit on Windows 10 with python 3.10, and macOS on python 2.7 and 3.10 and it worked here.
> 
> -CorpNewt

Arch LInux, Latest Python

**Comment by Apethesis** [comment]
> Also worth asking if you have the `clip` (should you be running Windows) or `pbcopy` (if you're on macOS/Linux) binaries. If not - I could wrap the copy check in a `try... except` block for that portion - and have it fall back on the regular tkinter clipboard functions if it fails. I might do that while I'm waiting for a reply - as it won't hurt anything regardless.
> 
> -CorpNewt

Yeah I don't seem to have them, cant get them from pacman either.
I think its more convenient to use the tkinter clipboard since its already installed to use propertree.

**Comment by corpnewt** [comment]
Yeah - since it wraps the attempts in a `try... except`, if no supported clipboard binaries are found, it only leverages the tkinter clipboard functions.  I'll close this issue though unless any other issues arise.

-CorpNewt
