### ISSUE TITLE
[Feature request] Import/Export profiles

### ISSUE THREAD

**Issue by dreamwhite** [corpnewt/ProperTree#131]
It would be nice to add a feature that lets users export their ProperTree configurations (like color presets etc)

**Comment by corpnewt** [comment]
Hey there,

That's an interesting idea that I hadn't considered before.  If I get some time, I may experiment with it to see what I can figure out.  In the meantime, though, all the custom configurations are stored in the `settings.json` file located in ProperTree's `Scripts` folder.  If you've built the .app bundle on macOS - this would be located at `ProperTree.app -> Contents -> MacOS -> Scripts -> settings.json`.  Copying this file to the target ProperTree's `Scripts` directory would effectively migrate configurations (though, I know it's manual, and not terribly convenient haha).

Thank you for the suggestion - I'll look into it,

-CorpNewt
