### ISSUE TITLE
HiDPI in Windows 10 bug

### ISSUE THREAD

**Issue by VictorGamer072YT** [corpnewt/ProperTree#14]
If you use any of the scaling options in Windows 10 [125%, 150%, 175%] The GUI looks distorted/lower res, Normally this is fixed by ticking an option in the compatibility menu, But that does not exists in a bat file, image for reference:
![Annotation 2020-02-15 141102](https://user-images.githubusercontent.com/44535997/74592202-b037f980-4ffd-11ea-8b21-07a81d758f96.png)

**Comment by corpnewt** [comment]
Not an issue with ProperTree - likely an issue with python itself or tkinter.  The .bat file will launch a python.exe interpreter - I'm guessing that is what you'd need to adjust in the compatibility menu.

-CorpNewt

**Comment by VictorGamer072YT** [comment]
Yeah, your right, going to close this for now.
