### ISSUE TITLE
OC version mismatch regardless of what I do on sample.plist from opencore packages

### ISSUE THREAD

**Issue by monkeyman4412** [corpnewt/ProperTree#141]
I'm on windows10, using latest version of python at the time of this writing (3.10.6)

It seems like the editor is bugged? at least on windows?

I looked up previous issues regarding version mismatch, and others suggested to restart from scratch and make sure it's all the same type (aka, don't mix debug with release)

However I'm still getting the problem, no matter what I do. I'll delete the entire folder, reset it up (leave all core components. aka OC/OpenCore.efi OC/Tools/openshell.efi. using it all from the same release variant. Aka debug in this case)
But it still reports that it has found a oc version difference on a clean unedited sample.plist. Directly from the opencore debug.

I'm kinda at a loss here, since I got everything setup before just fine. (installed mac os, ran it. fixed audio, graphics. etc. I don't recall it giving me this issue until a clean windows install) But I have reasons to use a clean plist, so I can setup two distinct sets of Opencore folders. One strictly for debug, and debug kexts. And the other for release and release kexts

**Comment by corpnewt** [comment]
All that is stating is that your ProperTree Settings have a different target OC version selected than the OpenCore.efi that you're using.  By default, ProperTree's Snapshot OC Version setting is set to "Latest", which is currently updated for OC 0.8.4 prerelease (as the schema has been changed from 0.8.3).  When you run an OC Snapshot, ProperTree compares the MD5 of your OpenCore.efi to those stored in its snapshot.plist file - and sees that the snapshot target doesn't match the file version - and is just asking which you would like to use.

As a rule of thumb - ProperTree always tries to suggest what is sane - so selecting "Yes" in any of its yes/no dialogs is a safe bet.

-CorpNewt
