### ISSUE TITLE
Wrong order of Kexts is not fixed by creating a snapshot

### ISSUE THREAD

**Issue by 5T33Z0** [corpnewt/ProperTree#142]
Recently, I am noticing an unusual large amount of help request on reddit for fixing non-working configs.

And in 8 out of 10 cases the reason why it's not working is because the order of kexts is incorrect. 

If I recall correctly, using the "OC Snapshot" function fixed this in previous versions of ProperTree.  But in the current version (I am using the app based on python 3.10.6), the order of kexts is no longer corrected when generating a snaphot.

Can you look into it?

Thanks

**Comment by corpnewt** [comment]
Please show me the incorrect order after an OC Snapshot

**Comment by 5T33Z0** [comment]
Before Snapshot:
![Bildschirmfoto 2022-09-06 um 20 29 40](https://user-images.githubusercontent.com/76865553/188712089-269a0af5-e35c-4a4f-8b3d-658756fef003.png)

After Snapshot
![Bildschirmfoto 2022-09-06 um 20 30 26](https://user-images.githubusercontent.com/76865553/188712137-12804b0f-dc37-41d6-be1d-7b2e41d05277.png)

Basically, the order is unchanged.

**Comment by corpnewt** [comment]
Because it doesn't nees to be? Which kext(s) are out of order there?

**Comment by 5T33Z0** [comment]
I thought Lilu and VirtualSMC have to be first since everything else relies on these 2?

No?

So it only matters to the ones which are considered "Lilu plugins"?

**Comment by corpnewt** [comment]
Read my edit in my first reply. 

Lilu and VSMC only need to load before anything that relies on them. This is already the case in your screenshots. The load order is fine there - and ProperTree has not reordered them because there is no reason to.
