### ISSUE TITLE
line 18     compare_to_version () {

### ISSUE THREAD

**Issue by bugs45** [corpnewt/ProperTree#149]
when I run    python3 ProperTree.command    in Mint I get the above error and subsequent errors after I deleted the bracket

**Comment by bugs45** [comment]
line 18
    compare_to_version () {

**Comment by corpnewt** [comment]
`ProperTree.command` is not a python file - it's a bash file.  You are likely following some outdated instructions.  Instead, try running `python3 ProperTree.py` - as that's the actual python file.

-CorpNewt

**Comment by bugs45** [comment]
Sorted, many thanks

regards

Chris Bugden
Axles Driving School 07805 626741
axleslearners.biz

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
