### ISSUE TITLE
Cannot Open - Permissions

### ISSUE THREAD

**Issue by redkurn** [corpnewt/ProperTree#15]
Readme does not state what permissions are needed, however I have tried setting all to read/write with no success.

Maybe I am doing something wrong here?

Right click -> Open

Error:
![Screen Shot 2020-02-20 at 8 00 16 AM](https://user-images.githubusercontent.com/2021174/74953996-4336b200-53b7-11ea-94b6-ac8b5e367f68.png)

Get Info:
![Screen Shot 2020-02-20 at 8 00 33 AM](https://user-images.githubusercontent.com/2021174/74954005-45990c00-53b7-11ea-913d-9913e28125ee.png)

**Comment by corpnewt** [comment]
It's likely just missing the execute permission.  You can add that via the following in terminal (replacing `/path/to/` with the actual path):
```
chmod +x /path/to/ProperTree.command
```
-CorpNewt

**Comment by asdf072** [comment]
It's not. This is still an issue.

**Comment by corpnewt** [comment]
@asdf072 have you added the execute permission via my prior comment above?  If so - can you send a screenshot of the terminal where you've run that, and of the dialog you get when double-clicking the `ProperTree.command`?

-CorpNewt
