### ISSUE TITLE
macOS Ventura EFI help

### ISSUE THREAD

**Issue by spitrip82** [corpnewt/ProperTree#152]
Hello my friends, I would love to install Ventura on my computer, but unfortunately I don't have the necessary skills to do it alone :(  I tried to go to the Olarila website  and I downloaded the Ventura iso and the EFI comet lake but at the end of the installation I always have problems , my network card is not detected and I can not connect to the internet
I tried to follow a youtuber from Brazil I tried to follow his step by step on how to configure the EFI and after installing ventura I see that it detects my network card but I can't access the internet again :( 
Could I kindly ask you to prepare me an EFI with these specifications? would make me the happiest person in the world!
I want to thank you in advance and I apologize for bothering you , a big hug from Portugal

CPU:          Intel Core i7-10700  (Processor Graphics  Intel® UHD Graphics 630) 
CHIPSET:      B460, Intel Comet Lake-S
GPU:    AMD Radeon RX 6600 // UHD Graphics 630
Network:         I225-V // 
Wireless-AC 9260

**Comment by ai19880612** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Fu-Yuxuan-hub** [comment]
[AppleIntelI210Ethernet.kext.zip](https://github.com/corpnewt/ProperTree/files/10145329/AppleIntelI210Ethernet.kext.zip)
[SSDT-I225V.aml.zip](https://github.com/corpnewt/ProperTree/files/10145334/SSDT-I225V.aml.zip)
Delete _SSDT-I225Ethernet.aml_         
Add _AppleIntelI210Ethernet.kext_ and _SSDT-I225V.aml_ to your OpenCore.        
Add _e1000=0_ to boot-args

Please have a try

**Comment by ricardosaeki** [comment]
Good night, friend all right, I saw that you are with a little difficulty, see this youtube channel, about OpenCore is in Portuguese Brazil, plus the guy who teaches and very good, I believe that if you activate automatic subtitles, you will understand well.
