### ISSUE TITLE
ProperTree taking minutes to launch

### ISSUE THREAD

**Issue by MasterRaccoon** [corpnewt/ProperTree#153]
I'm using Ventura in a laptop, and I'm taking at least 5min to open ProperTree, but after opened, I can use it normally.

I've tested different versions of Python3. 

On my desktop, ProperTree is working properly.

**Comment by corpnewt** [comment]
Hey there - sorry for the late reply to this.  How are you launching ProperTree?  If you're using `ProperTree.command` it will walk the PATH variable looking for all `python`, `python3`, and `py` binaries while keeping track of the highest py2 and py3 versions - then pipe `ProperTree.py` to the highest detected.

If you have a botched python install - it will be checked with the `-V` arg (which prints its version to `stdout` or `stderr`) each time the .command is started - and that could potentially cause stalls.

If you use `buildapp-select.command` from within ProperTree's `Scripts` directory, you can build a .app bundle with a hardcoded shebang that avoids that PATH var walking which may help.  The `buildapp-select.command` script will also show you what python installations were found - which may expose any oddities as well.

Not sure if any of that info will actually help - but it may expose if something is amiss.

-CorpNewt

**Comment by corpnewt** [comment]
I was able to have some other users test - and it seems it was stalling while checking for updates at start up.  I've scheduled the update check via the event loop to avoid it blocking - and implemented a simple boolean lock system to prevent mutltiple simultaneous checks in [this commit](https://github.com/corpnewt/ProperTree/commit/a42f3979dde18844a8cf11232e4f1a252c8cf18f).  When you get a chance, can you test and see if that fixes the issue for you?

-CorpNewt

**Comment by corpnewt** [comment]
I did some more digging and wrapped the update check with python's `multiprocessing` module to prevent the UI from being blocked while checking for updates in [this commit](https://github.com/corpnewt/ProperTree/commit/dc137245c29363e2005ebedc5b361693c0badcea).  I believe this has actually fixed the source issue.

-CorpNewt
