### ISSUE TITLE
'The application cannot be opened for an unexpected reason'

### ISSUE THREAD

**Issue by twio142** [corpnewt/ProperTree#154]
Error message:

The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10810 "kLSUnknownErr: Unexpected internal error" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2756, NSUnderlyingError=0x6000027f8de0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000027f8e40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}}}

**Comment by corpnewt** [comment]
Can you provide any more info? I've not seen anything like this before.

What OS, what py version, where did you get py from , are you running the .command or a built .app, etc?

**Comment by twio142** [comment]
macOS Ventura 13.1,

Python 3.10.8 (miniconda)

The error above comes from opening a built ProperTree.app.

Running `ProperTree.command` throws `ModuleNotFoundError: No module named 'Tkinter'` and `ModuleNotFoundError: No module named '_tkinter'`.

**Comment by twio142** [comment]
Oh right, running buildapp-select solved the problem. Thanks!
