### ISSUE TITLE
doesn't work for me 

### ISSUE THREAD

**Issue by User13244567** [corpnewt/ProperTree#159]
it gives me an error  
 File "/home/andre/Downloads/ProperTree-master/ProperTree.command", line 18
    compare_to_version () {
                          ^
SyntaxError: invalid syntax

_Originally posted by @kittywhiskers in https://github.com/corpnewt/ProperTree/issues/42#issuecomment-645907865_

**Comment by ai19880612** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by corpnewt** [comment]
How are you launching ProperTree?

-CorpNewt

**Comment by kittywhiskers** [comment]
@User13244567 My original comment was 3 years ago and a year ago, `ProperTree.command` was repurposed into a bash script (see https://github.com/corpnewt/ProperTree/commit/516e6e66c0b098bed03e18d551fb501c0573eeee) around a year ago, with the script itself being moved to `ProperTree.py` (see https://github.com/corpnewt/ProperTree/commit/ccc967ee3253dcd35386319c829e515da5bf16a7).

I've amended my comment to reflect this.

**Comment by corpnewt** [comment]
Yep - and I've replied on both this, and the linked issue thread.  Seems it's just a matter of outdated information.

-CorpNewt
