### ISSUE TITLE
Windows Python error when trying to execute OC Scapshot

### ISSUE THREAD

**Issue by r3dlobst3r** [corpnewt/ProperTree#16]
I am getting the following error when I try to do the OC Snapshot:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Andrew\Downloads\ProperTree-master\Scripts\plistwindow.py", line 1016, in oc_snapshot
    for tool in sorted(tools_list):
TypeError: '<' not supported between instances of 'dict' and 'dict'` 

Any help is appriciated

**Comment by corpnewt** [comment]
I looked into it - and it seems that python 2's dict sorting was quite involved behind the scenes, and python 3's relies more on the user to handle (hence the error about not being able to compare which is less than [`<`] which).  I implemented key-based sorting using `lambda x: x.get("Path","").lower()` in [this commit](https://github.com/corpnewt/ProperTree/commit/80f33755ac4a8000458cdafd4ee558d3a1cf8382) that may help prevent that problem as it specifically sorts based on the value of the "Path" key inside the dict - and offers an empty string if one doesn't exist.  If you could test and let me know if that worked, I'd appreciate it.

-CorpNewt
