### ISSUE TITLE
invalid file 

### ISSUE THREAD

**Issue by TarekmElmaghraby** [corpnewt/ProperTree#161]
when I select config.plist file it says it is invalid file

**Comment by corpnewt** [comment]
Well, the file is likely not a valid plist then. You could send it here to verify, but it doesn't sound like an issue with ProperTree unless you're sure of the integrity of the file.

-CorpNewt

**Comment by TarekmElmaghraby** [comment]
Yes it was not a valid Plist I have tried another one and worked     thank you
