### ISSUE TITLE
Focus issues on M1 Max - can't click text boxes most of the time

### ISSUE THREAD

**Issue by emaa10** [corpnewt/ProperTree#164]
Dear developers of this application,

Clicking in any text box on the M1 Max ends with clicks not being registered, as you can see in [this](https://youtu.be/EGqP90GFOFM) video. Python version / Built app doesn't matter.

Hardware:
- MBP 14" 2021
- M1 Max
- 32GB
- 1TB
- macOS 14.1 (23B74)

**Comment by corpnewt** [comment]
Assuming you're on Sonoma, this is a known issue currently.  I believe it's something to do with some change that Apple made which prevents click events from reaching the treeview.  As a workaround, if you drag the window around slightly that should "wake up" the treeview to clicks again.

You can also control most of ProperTree with the keyboard:

- Ctrl/Cmd + up/down arrows: Cycle the selected node's type
- Ctrl/Cmd + number keys: Select a specific type for the selected node
- Ctrl/Cmd + left/right arrows: Toggle boolean values of the selected node
- Enter: Start editing the first element of the currently selected node that can take input
- Tab: When editing with enter, moves to the next available column that can take input (if any)

If I find a workaround that's more complete, I'll post it to the FAQ, but for the time being this seems like an issue on Apple's end.

-CorpNewt

**Comment by emaa10** [comment]
Thank you very much for your quick reply, I didn't know about this fix and these shortcuts!
That also fixed the issue for me.

**Comment by corpnewt** [comment]
I just updated to python 3.12.0 on 14.2 b1 and that seems to have fixed the issue with clicks not working.  I confirmed by starting ProperTree.py with both python 3.11.3 and 3.12.0, and in 3.11.3 it still has the issue - with 3.12.0 clicks work as expected from the start.

-CorpNewt

**Comment by emaa10** [comment]
Thank you, that also fixed the issue for me! Thanks for the quick solution!

**Comment by corpnewt** [comment]
Glad to hear that fixed things for you too - I'll go ahead and update the FAQ with that as a solution.

-CorpNewt
