### ISSUE TITLE
OC Snapshot issue when checking configs for real Macs

### ISSUE THREAD

**Issue by 5T33Z0** [corpnewt/ProperTree#166]
Hi.

I've noticed an issue when using ProperTree's OC Snapshot function to check .plist used by OCLP. In my case, it's for an iMac11,3. Apparently, it removes some kexts required for getting legacy WiFi working again. 

List of kexts prior to snapshotting (Sceenshots are form OCAT since it's easier to see al kexts at once):

![Bildschirmfoto 2023-11-26 um 11 42 02](https://github.com/corpnewt/ProperTree/assets/76865553/3a1f3b44-1737-4d81-b4f7-854b485fa1f2)

After snapshotting:

![Bildschirmfoto 2023-11-26 um 11 44 41](https://github.com/corpnewt/ProperTree/assets/76865553/d24b9760-8707-40e8-8857-ab9f3731f987)

The following kexts were removed from the list by ProperTree:

- **corecaptureElCap.kext** 
- **IO80211ElCap.kext** (But the plugin is still in the list)

Is it possible to put kexts like these on some sort of ignore list? It took me quite some time to figure out that these entries were removed from the config when trying to fix Wi-Fi again 😄 

Greetings,
5T33Z0

**Comment by ai19880612** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by corpnewt** [comment]
This appears to be an issue with the kexts from OCLP, and not ProperTree.  Both of those kexts `CFBundleExecutables` do not match the actual executable names.

corecaptureElCap.kext's `CFBundleExecutable` is listed as `corecatpure`, but the actual binary is named `corecaptureElCap`.  IO80211ElCap.kext's `CFBundleExecutable` is listed as `IO80211Family`, but the actual binary is named `IO80211ElCap`.

Changing the `CFBundleExecutable` value within the Info.plist of each kext will fix ProperTree's detection in the OC Snapshot.

I've brought this to @khronokernel 's attention and they're already correcting it in OCLP's repo.  The bins should be updated with the corrections shortly.

-CorpNewt

**Comment by 5T33Z0** [comment]
Ah, okay. Thanks for the explanations

**Comment by corpnewt** [comment]
For sure.  I'm glad it's something relatively easily fixable.

-CorpNewt

**Comment by 5T33Z0** [comment]
I corrected the `CFBundleExecutable` names for both kexts and now ProperTree no longer kicks them out of the list.
