### ISSUE TITLE
macOS 11 (1107) or later required, have instead 11 (1106) !

### ISSUE THREAD

**Issue by nocontent06** [corpnewt/ProperTree#168]
Running macOS 11.7.10 latest Big Sur on my MacBookPro11,3

<img width="692" alt="image" src="https://github.com/corpnewt/ProperTree/assets/93335632/ed11f7b1-0b54-4b54-934a-915ea0430cc9">

<img width="1186" alt="image" src="https://github.com/corpnewt/ProperTree/assets/93335632/fc1f4325-d0e2-45ee-b43a-f94b420b8fa6">

**Comment by corpnewt** [comment]
That's not an issue with ProperTree - that's an issue with python/tk itself.  Try installing the [latest python](https://www.python.org/downloads/macos/) and see if that resolves it.  You're currently running python 3.8, which is fairly old and uses tk 8.5 IIRC (see documentation [here](https://www.python.org/download/mac/tcltk/)) which is rather buggy in macOS.

-CorpNewt
