### ISSUE TITLE
BrcmBluetoothInjector.kext mistakenly added into config.plist with CMD+R

### ISSUE THREAD

**Issue by Hochiss** [corpnewt/ProperTree#169]
Begin with macOS 12/Monterey, `BrcmBluetoothInjector.kext` is not needed and replaced by `BlueToolFixup.kext`:

cf.: https://github.com/acidanthera/BrcmPatchRAM, "Do not use it with BrcmBluetoothInjector for macOS 12 or newer"

But use CMD+R while building Snapshot, `BrcmBluetoothInjector.kext` is added into `config.plist` (w/o Max/Min-kernel limitation), thus BT n/a after reboot,remove the entry resolved.

please review it.

**Comment by ai19880612** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by corpnewt** [comment]
ProperTree's OC Snapshot just ensures the config.plist matches the directory contents.  It is still up to **you** to ensure it's configured correctly.  The script does not know what OS you intend to boot, nor does it have any prior knowledge of which kexts work where.  It ensures load order between the kexts in OC -> Kexts, and has some mild sanity checks - but that's it.

-CorpNewt
