### ISSUE TITLE
Tk TclError on Linux

### ISSUE THREAD

**Issue by tkmarsh** [corpnewt/ProperTree#17]
Hey, I'm not familiar with Tk so I'm pretty stumped about what's going wrong here, but trying to run this on Debian Bullseye/Linux 5.4.0 using Python 3.7 throws this error: 
```
Traceback (most recent call last):
  File "./ProperTree.command", line 554, in <module>
    p = ProperTree(plists)
  File "./ProperTree.command", line 173, in __init__
    self.tk.bind_all("<{}-,>".format(key), self.show_settings)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1118, in bind_all
    return self._bind(('bind', 'all'), sequence, func, add, 0)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1061, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: bad event type or keysym ","
```
I also tried running it with Python 2.7 and it yields the same.
I was originally missing the tk module and had to install it, could it possibly be a dependency or version mismatch issue? I think I'm running tk-0.1.0.

Thanks for all the time you've put into developing and supporting your tools so far.

**Comment by corpnewt** [comment]
Looks like linux didn't like the actual `,` character when binding keys.  I changed it to `comma` in [this commit](https://github.com/corpnewt/ProperTree/commit/59cd2a51617fdc29b1e7d369683c7a8f977a086f) which worked in Windows for me.  If you could test and confirm that fixes it in linux as well, I'd appreciate it.

-CorpNewt

**Comment by tkmarsh** [comment]
Yep that's it working and all in 10 mins!
Thanks a ton.
