### ISSUE TITLE
I can't see all the directories on Proper Tree (Windows)

### ISSUE THREAD

**Issue by rwneilands** [corpnewt/ProperTree#170]
The app opens fine but am I doing something wrong, all the standard stuff appears as in the acpi, drivers, kernel, tools but it looks like I'm missing a lot of directories, do I need to be on Linux or Mac to see the information, it's not a problem if I do I just thought I could do it from my daily driver machine
![image_2024-01-31_190646877](https://github.com/corpnewt/ProperTree/assets/123082991/8f122d87-e13e-47f2-a331-0a75af0f034f)

**Comment by ai19880612** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by corpnewt** [comment]
I'm not sure what you mean by directories in this context - but it looks like you've just performed an OC Snapshot into a blank document and then saved it.  The OC Snapshot (as outlined in [the FAQ](https://github.com/corpnewt/ProperTree#faq)) will walk the ACPI, Kexts, Tools, and Drivers folders and add/remove entries in ACPI -> Add, Kernel -> Add, Misc -> Tools, and UEFI -> Drivers respectively within the config.plist.

-CorpNewt

**Comment by rwneilands** [comment]
Very interesting, I used the sample.plist file and copy it over and renamed it like it said to and I downloaded all the required kexts, amls and efis, but I was really confused on what I was doing wrong, I eventually just went to google and found Ocat which is showing the stuff I couldn’t see before but the only thing now is I don’t have any nvram entries, I can get the usb to post to its start up, the built-in laptop keyboard and mouse don’t work but that’s fine for the moment I just want to get the installer to boot and the usb devices work fine, but when I click on macOS.dmg it loads the apple logo and the loading bar but that bar doesn’t move and I would look through verbose but I don’t have the nvram entries/arguments. Thanks for the assistance btw, I wasn’t sure if posting the issue here would get responded to.

**Comment by rwneilands** [comment]
Using ProperTree I opened the file with File > Open at the start it said Ctrl + R to select where the file was first, so I did that, but I got to point where in the screenshots on your instruction page I couldn’t do anymore because I was missing a lot of the settings, and I thought it was just a windows problem because you were doing all of it on a mac

Regarding the NVRAM problem, I was going to go over to their page for it and I have been looking elsewhere for what I’m supposed to do about it, do you mind having a look? I’ll attach a screenshot of ProperTree and what it’s telling me now that I can see what I was missing
![image_2024-02-01_083604807](https://github.com/corpnewt/ProperTree/assets/123082991/ce314cf0-5826-4ee8-933f-af0ee52c19c0)

**Comment by corpnewt** [comment]
> Using ProperTree I opened the file with File > Open at the start it said Ctrl + R to select where the file was first, so I did that, but I got to point where in the screenshots on your instruction page I couldn’t do anymore because I was missing a lot of the settings, and I thought it was just a windows problem because you were doing all of it on a mac

I didn't send any screenshots, nor are there any in the readme on this repo.  If you perform an OC Snapshot on the current config.plist you have opened in ProperTree in your above screenshot, does it remove those other elements?

-CorpNewt

**Comment by rwneilands** [comment]
Someone else must've made the guide [https://dortania.github.io/OpenCore-Install-Guide/]
Performing an OC Snapshot didn't do anything but expand everything out again

**Comment by rwneilands** [comment]
Ah okay, I'll close this and go to their support page, I'm not sure what I did for ProperTree to not show everything until after OCAT. Thanks a lot though it was very helpful.

-rwneilands
