### ISSUE TITLE
Root>Kernel>Add without any entry after "OC Clean Snapshot"

### ISSUE THREAD

**Issue by adielmachado** [corpnewt/ProperTree#171]
After doing an "oc clean snapshot" on my config.plist through propertree, apparently everything is filled in correctly. However, within Kernel>add no key is added and I have 11 kextx within my OC directory. Same behavior on Windows, on a MacBook Air, on propertree version 0.2.5 or the latest version. I'm using OpenCore 9.5.

**Comment by corpnewt** [comment]
With regard to kexts - in both snapshot variants, ProperTree will qualify each kext by verifying its extension, loading the Info.plist within, and ensuring any listed `CFBundleExecutable` exists.  If the kext is not a proper bundle with a valid Info.plist, or the executable listed is not present - it is omitted.

If no kexts are added after a snapshot in your situation - I would recommend verifying that your kexts are correct and valid.

-CorpNewt
