### ISSUE TITLE
Starting ProperTree under Mojave results into Logout

### ISSUE THREAD

**Issue by daslicht** [corpnewt/ProperTree#18]
When I start Propertree under Mojave  I get an immediate logout to the logscreen ?
Idea? Last time I tried it it worked.

**Comment by corpnewt** [comment]
I've not ever seen this before.  I'm not entirely sure how to even go about debugging it.  I've been using ProperTree on 10.12.6 and 10.15.0 through 10.15.4 without running into this issue.  I wonder if something beyond this script may be the culprit?

-CorpNewt

**Comment by daslicht** [comment]
I have no clue why this happens now, I remember that it was working the week before, I haven't changed a thing  weird. Are there somewhere logs ?

**Comment by daslicht** [comment]
I have now cleaned my bash_profile and ProperTree is working again.
To keep Spleeter working I just added the content above to the  Automator Workflow script directly :) Out of curiosity, do you see what could be interfering ?
