### ISSUE TITLE
Cannot open latest Propertree on Monterey 12.7.3 already tried update python to 3.13

### ISSUE THREAD

**Issue by SLCCL** [corpnewt/ProperTree#183]
Greetings, 
Cannot open Latest Propertree on Monterey 12.7.3 with Python 3.13.0. Already executed "buildapp-select.command" (C. Current (/usr/bin/env python3)) but the following shows when try to open "ProperTree.command"

```

➜  ~ /Volumes/Space/Downloads/ha24/ProperTree-master/ProperTree.command ; exit;
/Volumes/Space/Downloads/ha24/ProperTree-master/ProperTree.command: line 284: 10807 Segmentation fault: 11  "$python" "$dir/$target" "${args[@]}"

Saving session...completed.

[Process completed]

```

Any advice would be greatly appreciated. Cheers.

**Comment by corpnewt** [comment]
You'll want to use the direct path to the `python3` bin for 3.13, not the `env python3` shebang as the environment accessible by .app bundles is different than the environment accessible from the shell.  If you got python 3.13 from python.org, the correct path should be `/Library/Frameworks/Python.framework/Versions/3.13/bin/python3`

-CorpNewt

**Comment by SLCCL** [comment]
> You'll want to use the direct path to the `python3` bin for 3.13, not the `env python3` shebang as the environment accessible by .app bundles is different than the environment accessible from the shell. If you got python 3.13 from python.org, the correct path should be `/Library/Frameworks/Python.framework/Versions/3.13/bin/python3`
> 
> -CorpNewt
> 
> In rereading your original question, it looks like you're running ProperTree.command and not the ProperTree.app bundle - I'm wondering if it can't find python 3? If that's the case - you can have ProperTree.command install it for you (which will also update the PATH var, as well as install certificates) via `./ProperTree.command --install-python` which may also fix your issues. I'm currently running python 3.13 locally on macOS 15.1 (24B82) and PT works as expected:
> 
> ![image](https://private-user-images.githubusercontent.com/12772521/379796210-391d3eb1-2d6c-40da-8583-5185ae8d6701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjMzMzYsIm5iZiI6MTcyOTg2MzAzNiwicGF0aCI6Ii8xMjc3MjUyMS8zNzk3OTYyMTAtMzkxZDNlYjEtMmQ2Yy00MGRhLTg1ODMtNTE4NWFlOGQ2NzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEzMzAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjODE5ZjdiNTY3MmU2OGJjNTJlYzFhOTU0M2EzOTk1N2RlZjZkZTVkMjJkNmIxOGFmOTQ4ZDRlYzZmZTVhYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._ZKn5bnytm_jWvu-9CYpWlMeGcdadhk9vdC3M-bBTgI)

Thank you so much!! After changed the python 3 path to the path you provided. PT can open now!! THANK YOU!
