### ISSUE TITLE
Multiple opened files destroying selection

### ISSUE THREAD

**Issue by maroeldawwyp** [corpnewt/ProperTree#190]
When opening multiple plist files in tab mode (not window mode), the selection got destroyed.
Meaning when i select an item, the item selected will be above or under the desired item, not the desired item itself.

Hope you understand me, due to my bad language.

**Comment by maroeldawwyp** [comment]
I was testing on macOS, do not know about Windows.

**Comment by corpnewt** [comment]
Do you happen to have some visual references for what you mean?  Screenshots before/after, or similar?

Thanks,

-CorpNewt

**Comment by maroeldawwyp** [comment]
Oo, just gimme some time...

**Comment by maroeldawwyp** [comment]
Ok, just i can not do this right now.

But you can find the issue by yourself.

Just follow the below steps:

1. Modify macOS 'Interface' or 'Appearance' settings to allow tab mode 'always', not just in 'full-screen' mode
2. Open two plist files, one by one
3. Try selecting any item in the first file, then click the 2nd file tab to open it and select any item in it.
You will find the issue i am talking about.

You want for example to select 'ACPI' section, but the 'Booter' section wilp be selected instead, or vice versa

**Comment by corpnewt** [comment]
This is what I've attempted locally and it seems to work alright (unless I'm misunderstanding what the issue is).  I took a video of one of my attempts here:
https://github.com/user-attachments/assets/274186b9-200e-4418-bd05-17e33ad5aa7b

I tried selecting and editing the files in different combinations of orders as well, but was unable to reproduce the issue.

-CorpNewt

**Comment by maroeldawwyp** [comment]
OK, i will try reproduce the issue in a video ASAP...

**Comment by maroeldawwyp** [comment]
This is the issue i mean: https://www.icloud.com/iclouddrive/07eggWJAaFpGsUdc1Gah8svkw#Issue

Sorry for the bad quality.

**Comment by corpnewt** [comment]
I was able to reproduce the error on python 2 - but the same code works as expected on python 3 without issue.  That leads me to believe it may be a tkinter issue directly - and outside the scope of ProperTree itself.  Perhaps try installing the latest python 3 release and see if that fixes it (you would need to re-run `buildapp-select.command` and target the py 3 install for the .app to use it).

-CorpNewt

**Comment by maroeldawwyp** [comment]
Yes, true.

I am already using python2.
Didn't test python3 yet.

I will test and reply to you again...

**Comment by corpnewt** [comment]
Glad to hear that worked out.  I'm not sure what causes that issue in the first place - but since python 3 resolves it, I would imagine it's outside the scope of ProperTree's code.

-CorpNewt
