### ISSUE TITLE
Not getting all sections using ProperTree Clean Snapshot option

### ISSUE THREAD

**Issue by jvb0077** [corpnewt/ProperTree#33]
I got a problem with the Clean Snapshot option:

I renamed the Sample.plist to config.plist and I used the OC Clean Snapshot option. What I end up with is a config.plist with only the ACPI, UEFI, Kernel and Misc sections. They are properly populated, but the other sections mentioned in the guide: Booter, DeviceProperties etc. disappear.

Did anyone also have this issue, or know how to fix it?

**Comment by corpnewt** [comment]
Did you run the clean snapshot on an empty document? Or did you first open the config.plist and then clean snapshot?

-CorpNewt

**Comment by jvb0077** [comment]
Ahhh yes that's i,. I didn't know it works likes that 🤦‍♂️. Thank you for that easy solution!
