### ISSUE TITLE
Can't accept int value 2164483

### ISSUE THREAD

**Issue by wangyi6854** [corpnewt/ProperTree#36]
When change ScanPolicy from 0 to 2164483, which is the sum of OC_SCAN_FILE_SYSTEM_LOCK, OC_SCAN_DEVICE_LOCK, OC_SCAN_ALLOW_FS_APFS, OC_SCAN_ALLOW_FS_HFS, OC_SCAN_ALLOW_FS_ESP, OC_SCAN_ALLOW_DEVICE_SATA and OC_SCAN_ALLOW_DEVICE_USB, ProperTree prompts "Couldn't convert to an integer or float.".

When I open the oc config file after using a text editor changing the value, it says "invalid literal for int() with base 10: \u202d2164483\u202c".

Win10 2004, python 3.8

**Comment by corpnewt** [comment]
There are extra unicode characters on either end of whatever you're pasting in there.  It is not an integer value - and as such, will not cast correctly.

The bracketed contents below are the extra unicode data:
```
[\u202d]2164483[\u202c]
```

They appear to change the direction of the text formatting (with the first being a left to right override, and the second popping the directional formatting) - what language are you using with ProperTree?  If your native language is right-to-left, and this is a common issue - I can look into stripping these characters from all but String fields.

-CorpNewt

**Comment by wangyi6854** [comment]
Thanks!

After Adding "chcp 65001" to ProperTree.bat, the problem's gone.

My system code page is 936, which is Chinese. The direction is left-to-right. And I never used rtl direction ever. I don't know why this happened.

Maybe the problem is related to the python environment. I never seen this problem again after changing code page, even commented out "chcp 65001". 

Weird.
