### ISSUE TITLE
Tkinter Error: unknown color name "BACKGROUND"

### ISSUE THREAD

**Issue by SnowLeoo** [corpnewt/ProperTree#47]
Hello, i tried to run the ProperTree.command File and i got an error saying
```
Traceback (most recent call last):
  File "ProperTree.command", line 557, in <module>
    p = ProperTree(plists)
  File "ProperTree.command", line 21, in __init__
    self.tk = tk.Tk()
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: unknown color name "BACKGROUND"
```
- OS is Manjaro
- Everything is updated and tkinter is installed

**Comment by Dan593** [comment]
I have the same error in __init__.py, running on python 3.8.2 on Manjaro on Raspberry Pi 4. have updated everything; no known cause. my code runs on Win 10, win 7, vista. this occurs in a matplotlib call.

**Comment by Abhi011999** [comment]
https://archived.forum.manjaro.org/t/python-tkinter-execution-issues/154263/4

### **The above link fixes this issue and also explains the details.**
