### ISSUE TITLE
OCS: No schema for Arch at 6 Index

### ISSUE THREAD

**Issue by dreamwhite** [corpnewt/ProperTree#49]
After doing an OC Snapshot of a OpenCore 0.6.0 EFI, the property "Arch" makes the system unbootable.
Despite that user should use the latest version of OpenCore (this Monday OC 0.6.1 should be released), it might be useful to check the SHA256 hash of OpenCore.efi, so that ProperTree can avoid adding Arch property. An exception can be added if the user has activated the Vault, so the SHA256 hash of OpenCore.efi will be totally different from the vanilla one.

I Attach a screenshot for better understanding

![image](https://user-images.githubusercontent.com/17933708/92155175-3c3d3180-ee27-11ea-8968-8d62c663196b.png)

**Comment by kommtzeitkonrad** [comment]
I think the last message (`OC: Configuration requires vault but no vault provided!`) indicates your problem as OpenCore should boot even with settings it does not know. Provide all files for proper vaulting or change `Vault` settings in `config.plist`. See [Configuration.pdf](https://github.com/acidanthera/OpenCorePkg/blob/f9f9ff3de5341b7989f528bcabd0d28d36d5a162/Docs/Configuration.tex#L3407).

**Comment by dreamwhite** [comment]
> I think the last message (`OC: Configuration requires vault but no vault provided!`) indicates your problem as OpenCore should boot even with settings it does not know. Provide all files for proper vaulting or change `Vault` settings in `config.plist`. See [Configuration.pdf](https://github.com/acidanthera/OpenCorePkg/blob/f9f9ff3de5341b7989f528bcabd0d28d36d5a162/Docs/Configuration.tex#L3407).

Thank you for your reply but I already know the solution (Misc->Security->Vault = "Optional").

I attached only a screenshot for better understanding :)

**Comment by itztaylorau** [comment]
I have the same error with you, but mine doesn't have `OC: Configuration requires vault but no vault provided!` instead it said `OC: Watchdog status is 0`. It stays for a few seconds and then it become a black screen.
<a href="https://ibb.co/2gLDjDq"><img src="https://i.ibb.co/Qrq2629/IMG-20200907-095213.jpg" alt="IMG-20200907-095213" border="0"></a>

**Comment by dreamwhite** [comment]
Again, my screenshot is only an example for getting a reply from @corpnewt. Yours is not the scope of this issue 😅
