### ISSUE TITLE
OC Snapshot does not detect duplicate dependencies

### ISSUE THREAD

**Issue by PhantomR** [corpnewt/ProperTree#53]
ProperTree does not remove duplicate entries when using OC Snapshot.

For example, if using both VoodooI2C and VoodooPS2, they both contain an internal VoodooInput.kext and in this case, ProperTree adds two VoodooInput entries (albeit with different paths since each one belongs to its respective parent kext), which leads to an error when booting (kext already loaded).

I was thinking maybe this could be solved by removing duplicates with the same name when snapshotting (even if they have different paths).

**Comment by corpnewt** [comment]
Hmmm - I could look into this, but ultimately the user should be informed in what they're doing and not rely on blind luck to get things working correctly.

-CorpNewt

**Comment by PhantomR** [comment]
Thank you for your reply and for all the tools you've shared with us. May I suggest that at least the user is warned this conflict exists and it will cause a boot failure?

**Comment by corpnewt** [comment]
The latest commit should add a warning (in the same vein as disabled dependencies, incorrect load order), and will offer to disable the duplicates - feel free to test and verify.

-CorpNewt
