### ISSUE TITLE
clover config.plist 

### ISSUE THREAD

**Issue by roddy20** [corpnewt/ProperTree#6]
https://github.com/CloverHackyColor/CloverBootloader/blob/master/CloverPackage/CloverV2/EFI/CLOVER/config-sample.plist
cannot be opened
![Снимок экрана 2019-12-07 в 11 47 07](https://user-images.githubusercontent.com/5681302/70372450-d9def100-18e7-11ea-83a2-da56d78d87b8.png)

**Comment by roddy20** [comment]
PS both Mac and Win10, the same error

**Comment by roddy20** [comment]
error in string
<key>#SmbiosVersion</key>
<integer>0x0206</integer>
can it be HEX or number only? 518 ?

**Comment by roddy20** [comment]
solved, in original config file it must be string 0x0206, not integer

**Comment by vit9696** [comment]
Why is this being closed? Hexadecimal numbers in integers are supported by plist format by all major editors, and are not limited by the spec either. This remains being a bug, which should be fixed.

**Comment by roddy20** [comment]
see the comment above

**Comment by corpnewt** [comment]
Should be fixed as of [this commit](https://github.com/corpnewt/ProperTree/commit/bd6d0b000306cc8f595cb9873e2a86079ed9ddbd).  It seems this is a limitation of python's plistlib module (2.7 code [here](https://github.com/python/cpython/blob/2.7/Lib/plistlib.py#L465-L466) and 3.8 code [here](https://github.com/python/cpython/blob/3.8/Lib/plistlib.py#L359-L360)) assuming base-10 integers at all times.  I've monkey patched the `end_integer` function to check for the `0x` prefix and react accordingly.

It also mimics Xcode's approach of loading the hex, then displaying and saving as a base-10 integer.  I tested loading the Clover config-sample.plist with both python 2.7.16 and 3.7.5.

Please let me know if you have other issues with it,

-CorpNewt

**Comment by roddy20** [comment]
works OK now
