### ISSUE TITLE
Propertree Crashes Python in BigSur

### ISSUE THREAD

**Issue by Kasimiri** [corpnewt/ProperTree#67]
Every time I try to launch Propertree, Propertree doesn't start und Python crashes.
In Catalina Propertree works fine, but in BigSur I don't become Propertree to work.

**Comment by jackharvest** [comment]
Are you on Big Sur 11.1 perchance? I'm experiencing the same thing.

**Comment by Kasimiri** [comment]
Yes, I am on Big Sur 11.1 too.

**Comment by jackharvest** [comment]
> Yes, I am on Big Sur 11.1 too.

(Upgraded my Python version, and now its fixed -- edited my comment above; Replied to you so you'd get an alert or whatever).

**Comment by Kasimiri** [comment]
too bad, but the update has unfortunately not helped me either

**Comment by Thumbkin** [comment]
Same problem here since 11.1 big sur update.

**Comment by aymantop** [comment]
Me too with big sur 11.1

**Comment by castelar007** [comment]
same after update to 11.1

**Comment by sreehax** [comment]
It seems to be an issue with tkinter in the python 3.8 in the Big Sur 11.1 base system. Apple shipped a broken tkinter, looks like. The remedy i found was to install the latest Python 3.9.1 from python.org.

**Comment by proplaya23** [comment]
same issue here after updating to Big Sur 11.1. I have downloaded Python 3.9.1 but I still cannot use proper tree. Just trying to edit my config.plist because it is so convenient with the snapshot feature.

**Comment by bktiger86** [comment]
I am having issue as well after the Big Sur 11.1 update. Try the latest Python 3.9.1 also failed.

**Comment by sarahbingo** [comment]
Me too with Big Sur 11.1, Python 3.9.1 upgraded, doesn't help. Is there anyway we can do in meantime?

**Comment by ccolorcat** [comment]
Same problem after upgrade to Big Sur 11.1

**Comment by d4vid1** [comment]
hi everyone

1. first open terminal and get latest version of ProperTree with git or download as zip file and unzip it

`git clone https://github.com/corpnewt/ProperTree`

2. And then get and install this python version for Big Sur 

`wget https://www.python.org/ftp/python/3.9.1/python-3.9.1-macos11.0.pkg`

3. Go to the Script Folder of PropeTree to build a .app with

`./buildapp-python3.command`

4. and try to run a ProperTree.app from folder. Sorry for my English.

**Comment by cc-monkey** [comment]
Python unexpectedly exits when running propertree on big sur11.1!

**Comment by sarahbingo** [comment]
> hi everyone
> 
> 1. first open terminal and get latest version of ProperTree with git or download as zip file and unzip it
> 
> `git clone https://github.com/corpnewt/ProperTree`
> 
> 1. And then get and install this python version for Big Sur
> 
> `wget https://www.python.org/ftp/python/3.9.1/python-3.9.1-macos11.0.pkg`
> 
> 1. run or Click on this command tool from Python 3.9 folder in Applications
> 
> `Update Shell Profile.command`
> 
> 1. Go to the Scripts Folder of PropeTree to build a .app with
> 
> `./buildapp-python3.command`
> 
> 1. and try to run a ProperTree.app from folder. Sorry for my English.

Thing goes exactly the same, no luck.

**Comment by Thumbkin** [comment]
In terminal if `python --version` gives something like "Pything 2.7.16"  then python will use a v2 instead of v3.
For me it worked in terminal when i did following: `python3 ProperTree.command`
This way it was forced to use python v3 instead of v2

**Comment by superbogie** [comment]
I too couldn't launch Propertree under BS 11.1 without getting the Python error. I tried everything in the comments above up to and including the buildapp sequence (along with Homebrewing the latest Python 3.9.1) but that gave me a "can't find '__main__' module" error when trying to run the newly created ProperTree.app in Terminal. I finally had success with the "python3 Propertree.command" method where I typed the "python3" part in Terminal and then dropped the Propertree.command file after that (where it lists the path to the command) and it now successfully opened a new Plist. Unfortunately, I can't double-click the OpenCore config.plist I'm trying to edit and instead, have to open it through the Python app File menu that is now opened. Hopefully, that's helpful to those struggling to run ProperTree under BS 11.1.

**Comment by kelvinjou** [comment]
I used my other hackintosh, which had 11.0.1 and python opened up. It seems like from 11.1 Beta and onwards, it would quit.

**Comment by corpnewt** [comment]
If I remove all third party installs of Python and run either the `ProperTree.command` or the .app built with the `buildapp-pythonX.command` - I'm met with the same issues that have been posted here:

![image](https://user-images.githubusercontent.com/12772521/102423824-7645d400-3fcf-11eb-81eb-4e48935de093.png)

If I download python 3.9.0 from python.org (linked [here](https://www.python.org/ftp/python/3.9.0/python-3.9.0-macosx10.9.pkg)), install it, then create the .app bundle with the `buildapp-python3.command`, I'm met with the following - which is how I have been running it with Big Sur since the early betas:

![image](https://user-images.githubusercontent.com/12772521/102423947-c2911400-3fcf-11eb-8fdc-977485ef76a7.png)

I have added a note about this in the [readme's FAQ section](https://github.com/corpnewt/ProperTree/blob/master/README.md#faq).  I don't personally use any package managers like `brew` - but I have heard that people have had issues due to it still linking to the system version of `tk`, which is the source of the issue. There was a user (kdorsel) that posted the steps they used to update their `brew` installation of python [here](https://github.com/corpnewt/ProperTree/issues/66#issuecomment-745413373).

Ultimately, this all seems to be an oversight on Apple's part with Big Sur shipping with a version of `tk` that it doesn't support.  They may or may not correct it - but I've personally had no issues using python 3 from python.org + the `buildapp-python3.command` running it on my machines.

-CorpNewt

**Comment by corpnewt** [comment]
Here's an interesting twist - it seems that the standard version of python in 11.2 has fixed the issue without the need for python3:

![image](https://user-images.githubusercontent.com/12772521/102436566-7e594000-3fde-11eb-8a10-652c5627256d.png)

![image](https://user-images.githubusercontent.com/12772521/102436621-9e88ff00-3fde-11eb-8776-bcd6e5b115f7.png)

I do have a quick revision to the `buildapp-[whatever].command` files that allows users to pick which python version they would like hardcoded in the .app bundle's "executable" shebang - but even using the `#!/usr/bin/env python` on 11.2 seems to work there, so it seems Apple may have fixed this issue:

![image](https://user-images.githubusercontent.com/12772521/102436821-017a9600-3fdf-11eb-886a-b0f65cbb0b63.png)

-CorpNewt

**Comment by corpnewt** [comment]
With [this commit](https://github.com/corpnewt/ProperTree/commit/a6d7025ba0ad228e303806b096d815a9cd59d3df) I have added a `buildapp-select.command` which should serve up all available py and tk versions found in the path var (including a suggestion of tk 8.6 for 11.x) and allow the user to pick which they would like hardcoded in the .app shebang:

![image](https://user-images.githubusercontent.com/12772521/102437736-a5b10c80-3fe0-11eb-82fc-e0dcf2368ef3.png)

![image](https://user-images.githubusercontent.com/12772521/102437772-b2356500-3fe0-11eb-8ab8-482378b80546.png)


Hopefully that information, plus Apple's changes will fix this for most users.

-CorpNewt

**Comment by junglegao** [comment]
> hi everyone
> 
> 1. first open terminal and get latest version of ProperTree with git or download as zip file and unzip it
> 
> `git clone https://github.com/corpnewt/ProperTree`
> 
> 1. And then get and install this python version for Big Sur
> 
> `wget https://www.python.org/ftp/python/3.9.1/python-3.9.1-macos11.0.pkg`
> 
> 1. run or Click on this command tool from Python 3.9 folder in Applications
> 
> `Update Shell Profile.command`
> 
> 1. Go to the Scripts Folder of PropeTree to build a .app with
> 
> `./buildapp-python3.command`
> 
> 1. and try to run a ProperTree.app from folder. Sorry for my English.

Thanks, solved my problem.

**Comment by aymantop** [comment]
> 1. python
solved my problem.

**Comment by Kasimiri** [comment]
> > hi everyone
> > 
> > 1. first open terminal and get latest version of ProperTree with git or download as zip file and unzip it
> > 
> > `git clone https://github.com/corpnewt/ProperTree`
> > 
> > 1. And then get and install this python version for Big Sur
> > 
> > `wget https://www.python.org/ftp/python/3.9.1/python-3.9.1-macos11.0.pkg`
> > 
> > 1. run or Click on this command tool from Python 3.9 folder in Applications
> > 
> > `Update Shell Profile.command`
> > 
> > 1. Go to the Scripts Folder of PropeTree to build a .app with
> > 
> > `./buildapp-python3.command`
> > 
> > 1. and try to run a ProperTree.app from folder. Sorry for my English.
> 
> Thanks, solved my problem.

Thanks, solved for me too.
