### ISSUE TITLE
No module named as Tkinter. (Linux, Arch)

### ISSUE THREAD

**Issue by phoenix277yt** [corpnewt/ProperTree#69]
i don't know whats happening imma leave the terminal output here.
`[daksh_s@R53600X ~]$ python ./ProperTree/ProperTree.command
Traceback (most recent call last):
  File "./ProperTree/ProperTree.command", line 5, in <module>
    import Tkinter as tk
ModuleNotFoundError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ProperTree/ProperTree.command", line 10, in <module>
    import tkinter as tk
  File "/usr/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
[daksh_s@R53600X ~]$ 
`

**Comment by phoenix277yt** [comment]
solution - install tk package in pamac repository

**Comment by hanspeteroliver** [comment]
What did you install? I have everything (tk, tcl) installed via pacman and still get this error

**Comment by hanspeteroliver** [comment]
@phoenix277yt

**Comment by phoenix277yt** [comment]
> @phoenix277yt

hey man, its been 3 years. i have 0 idea.
