### ISSUE TITLE
when use add kext at Kernel item , 'MatchKernel' is added ,not 'Max/MinKernel'

### ISSUE THREAD

**Issue by Resunny** [corpnewt/ProperTree#7]
when use add kext at Kernel item , 'MatchKernel' is added ,not 'Max/MinKernel'.

**Comment by corpnewt** [comment]
Are you referring to the right-click menu?

-CorpNewt

**Comment by Resunny** [comment]
> Are you referring to the right-click menu?
> 
> -CorpNewt

Yes, it is this function.
Found that you have fixed the problem.
Thank you!

**Comment by corpnewt** [comment]
Not a problem - I'll close this issue then!

-CorpNewt
