### ISSUE TITLE
Linux HiDPI Font issue: Fonts cut off

### ISSUE THREAD

**Issue by neuhaus** [corpnewt/ProperTree#71]
I am running it on Ubuntu on a 5120x2880 27" monitor.
The lower half of the text get cut off so the text is unreadable. It looks as if there is not enough room for the chosen font size.
I am attaching a screenshot below

![issue](https://user-images.githubusercontent.com/631764/102928772-a0990500-4499-11eb-9e3e-8d83fe867a76.png)

Note: This is a different issue than issue #55 where the user is getting fonts that are merely too small

**Comment by corpnewt** [comment]
This appears to be an issue with tk and outside the scope of ProperTree unless shown otherwise - as the treeview uses the display defaults.

-CorpNewt

**Comment by neuhaus** [comment]
Thanks - do you know where i can report this with the creators of this widget?

**Comment by denisps** [comment]
#80 Should resolve this issue
