### ISSUE TITLE
[Feature request] Add support to drag entries or items in array

### ISSUE THREAD

**Issue by 1alessandro1** [corpnewt/ProperTree#73]
When adding a new entry, (or when a new kext needs to be on top of the array, e.g Lilu) currently the only way to do it is to duplicate the plist file and copy-paste the entries one by one in the order which allows us to add only from the bottom, not by dragging. 

It can also be useful to add an option to sort in alphabetical order, that can be useful when adding a new `Quirk` to a `dict`

Can this be implemented somehow? As shown here in a different editor (written in C++)

https://user-images.githubusercontent.com/46293832/103661859-7eaa8280-4f6f-11eb-99e2-d37263e22cfb.mov

**Comment by corpnewt** [comment]
ProperTree has drag handles for each element in the far right column which can be used to drag and drop:

https://user-images.githubusercontent.com/12772521/103662317-674ea380-4f35-11eb-979b-ecb2edaa5c18.mov

You can also drag parent items, and all children follow (as shown below with nested elements):


https://user-images.githubusercontent.com/12772521/103662918-1e4b1f00-4f36-11eb-81da-710ba8bc85a2.mov

Regarding alphabetical order - in the settings, enabling the "Ignore Dictionary Key Order" checkbox and saving will yield a sorted plist, but I could look into adding a right-click option (or similar) to sort keys as well:

![image](https://user-images.githubusercontent.com/12772521/103662505-a846b800-4f35-11eb-9a26-bcdfcb05630a.png)

-CorpNewt

**Comment by 1alessandro1** [comment]
Perfect! Thank you for your clarifications. The right click option is a good idea indeed.
To drag the items, what about holding `Option` pressed to have a handy shortcut, or maybe emulating what the Xcode plist editor does, when you hold the entry pressed (insead of going always to the very end of the line)?

Another little issue, I found that in Catalina, 10.15.7, when building the app with python3, this happens:

(I had to compress the video with `libx265`, use mpv or similar if you have trouble to preview)


https://user-images.githubusercontent.com/46293832/103664950-1f4e7180-4f73-11eb-850f-1ad33c303a0c.mov

**Comment by corpnewt** [comment]
The issue with the coloring has to do with the tkinter version - it's only half-supporting dark mode, so some elements change, but not all.  I'd have to find a way to manually theme every element to work around it - or you could try another python version.  I had the same issue when using the "universal" install package of 3.9.1 from python.org.  The regular one worked fine though.

I can look into other options for dragging - but I don't have a timeline for that as it's non-essential currently.  I may be able to push the right-click -> Sort keys functionality quickly though.

-CorpNewt

**Comment by corpnewt** [comment]
The right-click "Sort keys" option was added in [this commit](https://github.com/corpnewt/ProperTree/commit/89f12a79f54f115e3afa4476e383a5fcf5a64d28).

-CorpNewt

**Comment by corpnewt** [comment]
And with [this commit](https://github.com/corpnewt/ProperTree/commit/b57eea3538d4fb8d38874c0586159182dff75cac) you can now drag the items from any point (it does have a "dead zone" before the drag initiates to prevent accidental reordering).

-CorpNewt

**Comment by 1alessandro1** [comment]
Thanks. Do you think we can leave this open until these are fixed?

* The coloring that has to do with the tkinter version (custom icons?)
* Other options for dragging even though it could take more time

**Comment by 1alessandro1** [comment]
Closing as solved, thanks again
