### ISSUE TITLE
Empty array tags does NOT end like this <array/>

### ISSUE THREAD

**Issue by leon9078** [corpnewt/ProperTree#77]
I found this small issue. Whenever I edit the config.plist, ProperTree will save every empty array tag in two split lines like so

<array>
</array>

instead of an inline solution –>  <array/> (like Xcode does)

This behaviour happens even for already <array/> tag present in the config, e.g. Sample.plist in latest OC (ref: https://github.com/acidanthera/OpenCorePkg/blob/0.6.5/Docs/Sample.plist#L747-L748)

**Comment by corpnewt** [comment]
I should be able to look into this shortly - it shouldn't be difficult to add for both arrays and dicts.

-CorpNewt

**Comment by corpnewt** [comment]
I tested on my copy with Python 3.8.7 in Windows 10 - but all the empty arrays and dictionaries already leveraged the `<array/>` and `<dict/>` approach (possibly a difference with between python 2 and 3's `plistlib`?).  When using inline data tags, ProperTree adjusts the plist after serializing - so I just leveraged that existing code to also check for empty arrays and dicts in [this commit](https://github.com/corpnewt/ProperTree/commit/957e75003582e3e03c65a126972e9d139ecf2b63).  Hopefully that yields the functionality you were looking for.

-CorpNewt

**Comment by leon9078** [comment]
Yeah, in the meantime I actually found that building the application bundle (.app) actually works (leaving <array/>). Instead, if I run from the .command, the problem exist.

Anyway, I just try with the new commit and it works perfectly in any circumstance. Thank you!! 😉🎉

**Comment by corpnewt** [comment]
Sounds like it is the python 2 `plistlib` serialization that causes the double tags then - glad the commit fixed it.

-CorpNewt
