### ISSUE TITLE
Copy and paste or drag function requirements

### ISSUE THREAD

**Issue by Resunny** [corpnewt/ProperTree#8]
Can you add copy-paste or drag-and-drop functionality to this tool?
This feature is needed when editing multiple files at the same time.
Thank you!

**Comment by corpnewt** [comment]
Copy+paste already exists.  You can also drag to re-order elements of the current plist, but Finder/Explorer interaction via tkinter isn't possible as far as I'm aware (at least not without reworking much of the script from the ground up).

With regard to copying, the script will format the xml representation of whatever you have copied to the clipboard.  Copying the following:
![image](https://user-images.githubusercontent.com/12772521/70750778-af7ca180-1cf4-11ea-94c5-cc0e7ad50892.png)
Results in the following being copied to the clipboard:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Some list</key>
	<array>
		<string>Item 1</string>
		<string>Item 2</string>
		<string>Item 3</string>
		<string>Item 4</string>
	</array>
</dict>
</plist>
```
Which can then be pasted into another window, or into a plain-text file.

-CorpNewt

**Comment by Resunny** [comment]
> Copy+paste already exists. You can also drag to re-order elements of the current plist, but Finder/Explorer interaction via tkinter isn't possible as far as I'm aware (at least not without reworking much of the script from the ground up).
> 
> With regard to copying, the script will format the xml representation of whatever you have copied to the clipboard. Copying the following:
> ![image](https://user-images.githubusercontent.com/12772521/70750778-af7ca180-1cf4-11ea-94c5-cc0e7ad50892.png)
> Results in the following being copied to the clipboard:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>Some list</key>
> 	<array>
> 		<string>Item 1</string>
> 		<string>Item 2</string>
> 		<string>Item 3</string>
> 		<string>Item 4</string>
> 	</array>
> </dict>
> </plist>
> ```
> 
> Which can then be pasted into another window, or into a plain-text file.
> 
> -CorpNewt

Oh!
I found the copy-paste function, but it seems that only one item can be copied at a time. Does this tool have multiple selection capabilities?
Thank you!

**Comment by corpnewt** [comment]
There isn't multiple selection as the hierarchy of items cannot be preserved depending on what the user selects - I mimicked Xcode's single-selection for this purpose.  If you select a parent element, all children of that parent are also copied (as in the `Some list` example above).  I'm contemplating whether to reorganize the top level to display it contained in a "Root" element the way Xcode currently shows it - but that would take some time/work to accomplish as I'd need to change multiple things in the code.

-CorpNewt

**Comment by corpnewt** [comment]
The "Root" node support was added as of [this commit](https://github.com/corpnewt/ProperTree/commit/c38ac119621ec0a916150db317367094785ef3e8) which allows for copying/pasting the plist in its entirety as needed.

-CorpNewt
