### ISSUE TITLE
Naming OpenShell.efi instead of UEFI Shell when doing OC snapshot

### ISSUE THREAD

**Issue by perez987** [corpnewt/ProperTree#82]
Dear friend, working with OC config.plist, when doing OC snapshot (Cmd + R or Cmd + Shift + R) ProperTree writes _OpenShell.efi_ as _Name_ of the tool but in this way the OC menu does not show the Shell icon, instead it shows the Tool icon.
The _Name_ key must be specifically _UEFI Shell_ for OC to correctly display _OpenShell.efi_ with the Shell icon.
It would be a good idea to change this behavior of ProperTree so that, when you fill in the _OpenShell.efi_ name in config.plist, it writes _UEFI Shell_.
See [here](https://www.insanelymac.com/forum/topic/344251-opencanopy-icons/?do=findComment&comment=2751421)
Thanks!!!

**Comment by ai19880612** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
