### ISSUE TITLE
Rewrite it with Swift

### ISSUE THREAD

**Issue by startpenghubingzhou** [corpnewt/ProperTree#9]
Could I try to rewrite it with Swift?

**Comment by corpnewt** [comment]
Of course! I'd just ask that anything you use from my project gets attribution. Beyond that, you're more than welcome to rewrite it.

-CorpNewt

**Comment by startpenghubingzhou** [comment]
> Of course! I'd just ask that anything you use from my project gets attribution. Beyond that, you're more than welcome to rewrite it.
> 
> -CorpNewt

Thx very much for your reply ！:)  However I still have some question about this project. How can I decompose all pycs in your project？

**Comment by corpnewt** [comment]
You don't need to decompile anything. All the code is in the .command and .py files. As for the gui, it makes sense that it would need a rewrite if you're migrating it to swift.

-CorpNewt

**Comment by startpenghubingzhou** [comment]
> You don't need to decompile anything. All the code is in the .command and .py files. As for the gui, it makes sense that it would need a rewrite if you're migrating it to swift.
> 
> -CorpNewt

Gotcha！ I ll start rewriting  tomorrow！ Thx for your answers very much! ^^

**Comment by vasanthdeveloper** [comment]
It would be great if the rewrite could support multiple operating systems because not everyone has a macOS system.

**Comment by corpnewt** [comment]
I'm going to close this as it's not actually an issue with ProperTree.

-CorpNewt
