### ISSUE TITLE
ProperTree font size cannot be changed

### ISSUE THREAD

**Issue by alexboro3191** [corpnewt/ProperTree#90]
I wonder if there is an opportunity to somehow increase the font? This is not provided in the settings.

**Comment by corpnewt** [comment]
Implemented in [this](https://github.com/corpnewt/ProperTree/commit/50dd89252107d06a33c144830ac7c547964c6e9e) and [this](https://github.com/corpnewt/ProperTree/commit/f55e8ee7b569c09df94176fc652d597e4804f902) commit.

-CorpNewt
