### ISSUE TITLE
it's black and can't see anything on macOS Monterey

### ISSUE THREAD

**Issue by andrewlsa** [corpnewt/ProperTree#91]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/63772067/121292101-fb28ff00-c91b-11eb-90f9-2452eb98538a.png">
<img width="535" alt="image" src="https://user-images.githubusercontent.com/63772067/121292200-23186280-c91c-11eb-9f8b-a736041020b9.png">
same in preferences

**Comment by corpnewt** [comment]
Can you install python from python.org and then build the .app bundle via the `buildapp-select.command` from the Scripts folder and see if that works properly? This looks like a tk bug wih the built-in version.

**Comment by andrewlsa** [comment]
> Can you install python from python.org and then build the .app bundle via the `buildapp-select.command` from the Scripts folder and see if that works properly? This looks like a tk bug wih the built-in version.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/63772067/121331310-56251b00-c949-11eb-95c1-2ab02799257f.png">
mhm~it works. Cheers.

**Comment by AboodeDaBOSS** [comment]
> 

can u help please I don't understand I have same problem 
<img width="743" alt="image" src="https://user-images.githubusercontent.com/68856095/228682077-e58267f8-e44f-4a95-bcb6-66dd421a9091.png">
