### ISSUE TITLE
Pressing CMD + SHIFT + O or CMD + SHIFT + R as advised in opencore config.plist setup webpage does nothing... Am I doing anything wrong?

### ISSUE THREAD

**Issue by friguron** [corpnewt/ProperTree#93]
Hi, I'm using Mojave 10.14.6 (with python 3.8 and 2.7 from macports, I had to instal py27-tinker and or py38-tinker for the script to work) and according to this page: https://dortania.github.io/OpenCore-Install-Guide/config.plist/#creating-your-config-plist I should press CMD/CTRL + SHIFT + O   o  CMD/CTRL + SHIFT + R to enable certain functionalities of ProperTree.

Apparently nothing happens on screen, so I'm somewhat puzzled and blocked in my way to create a proper config.plist
No matter what keys and or variations of the aforementioned key combinations I press, I get nothing on screen, just an empty plist being shown inside ProperTree window (which OTOH loads perfectly)

Any hint? My keyboard layout is ISO-Spanish.

**Comment by corpnewt** [comment]
If the keybinds aren't working for you - you can always use the File menu to perform whatever actions you need.  Mind you, there is no `cmd/ctrl + shift + O` keybind, just `cmd/ctrl + O` (which would be at File -> Open).

-CorpNewt

**Comment by friguron** [comment]
I wish I had a File menu, but apparently the script seems to be unable to
create any menu either...

[image: Captura de pantalla 2021-07-18 a las 14.35.47.png]

I'm sure there's some faulty library around (?), and I'm not aware of it...
But actually, I don't have any idea...

Besides, when I invoke the ./ProperTree.command from my MacOS Mojave,
there's no error in the command line bash terminal, so I'm lost.

**Comment by corpnewt** [comment]
The file menu is in the menubar on macOS:

![image](https://user-images.githubusercontent.com/12772521/126349574-5c8f0feb-a042-4a82-b429-e6cf91b3a3c5.png)

-CorpNewt

**Comment by friguron** [comment]
Nope!

![Captura de pantalla 2021-07-20 a las 17 17 23](https://user-images.githubusercontent.com/3338420/126350037-537759a5-7411-4b76-8512-5c757b1bae38.png)

XQuartz seems to be the owner of the window, not Python...
Can't say more...

**Comment by friguron** [comment]
If I use that script you recommended md, that's all I'm getting:
![bad_build_script_proper](https://user-images.githubusercontent.com/3338420/126359705-4c0f906a-aea6-4813-9eb5-54a89d95f1b5.png)


> An error occurred!
> '>=' not supported between instances of 'str' and 'NoneType'

In the screenshot attached you can also see which version of python I'm using...
I'm using macports and not homebrew (just in case it's useful data).

**Comment by friguron** [comment]
Unexpected (DELAYED!!) success (?)

Apparently ProperTree doesn't know how to handle properly working MacPorts python/python3 installations.

Today, many months ago, I had a sudden hunch and installed the "official" python 3.10.X binaries for MacOS (Mojave) from the actual python.org website (after uninstalling thoroughly the whole python/python3 working MacPorts version I've been using for years)... What happened? everything seems to work as expected!!

Can't say it's a succes story (it seems to be), but maybe some fix might be needed in ProperTree to be able to use (otherwise) proper MacPorts python/python3 installations me and some other users were using...

For the moment I'll survive with these Python official binaries!
