### ISSUE TITLE
Incorrect kext sorting in config.plist with Clean Snapshot

### ISSUE THREAD

**Issue by Edhawk64** [corpnewt/ProperTree#94]
Using the latest version of ProperTree, with Python 3.9.6 installed.  I created the ProperTree application using the buildapp-python3.command.

When running the OC Clean Snapshot option from the ProperTree/Python File menu the kexts are not sorted in the config.plist as expected, with Lilu.kext followed by VirtualSMC.kext and the rest alphabetically.

What is happening is that IntelMausi.kext is being placed first in the list of kexts, followed by Lilu.kext, USBInjectAll.kext and then VirtualSMC.kext, as can be seen in this screenshot.

![Screenshot 2021-07-14 at 18 03 31](https://user-images.githubusercontent.com/76566397/125663181-edfe00b0-b50e-4d06-84ae-b53a04424463.png)

Every other version of ProperTree I have used has placed Lilu.kext and VirtualSMC.kext first and second.  What has changed in the July 6th 2021 version?

**Comment by corpnewt** [comment]
I added support for kexts nested within folders inside the OC -> Kexts directory recently.  In doing so, I removed any hardcoded order - and let everything resolve based on comparing CFBundleIdentifiers to OSBundleLibraries.  The Dortania guide specifies that Lilu and VirtualSMC need to be first - but this is more of a way to prevent noob mistakes.  Lilu just needs to load before anything that depends on it (which is what ProperTree checks with the CFBundleIDs and OSBundleLibs).  In your list, IntelMausi is first - which does not depend on Lilu, so its load order in relation to Lilu is unimportant.

Essentially, it's working as it should - and still verifying load order, it just doesn't hardcode Lilu + the SMC emulator at the top.

-CorpNewt
