### ISSUE TITLE
Incorrect creation of the kext map

### ISSUE THREAD

**Issue by alexboro3191** [corpnewt/ProperTree#96]
![Без имени](https://user-images.githubusercontent.com/52546169/128630168-ec530234-7b95-46f4-afee-3b3889e72da8.png)
Lilu, Virtual, Green are registered by chance. 

Arch is not in the first place. Because of this, the bootloader is not working

**Comment by corpnewt** [comment]
> Arch is not in the first place. Because of this, the bootloader is not working

Are you talking about the order of the keys?  Those don't matter as they're not accessed by position, but by the key itself (as is standard for dictionaries).

-CorpNewt

**Comment by alexboro3191** [comment]
> > Arch is not in the first place. Because of this, the bootloader is not working
> 
> Are you talking about the order of the keys? Those don't matter as they're not accessed by position, but by the key itself (as is standard for dictionaries).
> 
> -CorpNewt

Sorry, but you are wrong. If you save config.plist like this, then OpenCore will not load. If you were kind enough to fix this, I would be very grateful.
Thank you for the ProperTree project. This is a very successful solution.

**Comment by corpnewt** [comment]
![image](https://user-images.githubusercontent.com/12772521/129115549-155deff7-95a0-4ea6-8ac3-2b4359e1a284.png)

I just saved my config.plist like this (matching the key order in your screenshot) - and rebooted without issue.  The whole purpose of a dictionary is to be able to access elements regardless of position - so having them still rely on position makes no sense.

-CorpNewt

**Comment by alexboro3191** [comment]
> ![image](https://user-images.githubusercontent.com/12772521/129115549-155deff7-95a0-4ea6-8ac3-2b4359e1a284.png)
> 
> I just saved my config.plist like this (matching the key order in your screenshot) - and rebooted without issue. The whole purpose of a dictionary is to be able to access elements regardless of position - so having them still rely on position makes no sense.
> 
> -CorpNewt

Thank you, I understand you. A moeno somehow to make Lilu / Virtual / Green are registered in order?

**Comment by alexboro3191** [comment]
> ![image](https://user-images.githubusercontent.com/12772521/129115549-155deff7-95a0-4ea6-8ac3-2b4359e1a284.png)
> 
> I just saved my config.plist like this (matching the key order in your screenshot) - and rebooted without issue. The whole purpose of a dictionary is to be able to access elements regardless of position - so having them still rely on position makes no sense.
> 
> -CorpNewt

Thank you, I understand you. Is it possible to somehow make Lilu / Virtual / Green register in order?

**Comment by corpnewt** [comment]
When you snapshot, the Info.plist of every kext within the Kexts folder is opened, the CFBundleIdentifier and OSBundleLibraries values are read - and compared to ensure that any kext that is

**Comment by alexboro3191** [comment]
> При моментальном снимке открывается Info.plist каждого kext в папке Kexts, значения CFBundleIdentifier и OSBundleLibraries считываются и сравниваются, чтобы убедиться, что любой kext, зависящий от другого в папке Kexts, загружается после него. Это также объясняет дубликаты CFBundleIdentifiers, которые пересекаются (проверяются через значения MinKernel и MaxKernel) - и предложит отключить все, что неправильно настроено.
> 
> Поскольку VirtualSMC, AppleALC, WhateverGreen и т. Д. Все перечисляют Lilu в своих OSBundleLibraries, все они будут загружаться после каждого снимка Lilu.
> 
> -CorpNewt

I understand, sorry to distract you. Thank you very much for your work. The ProperTree / GenSmbios / SSDTTime projects are very good!)

**Comment by corpnewt** [comment]
Not a problem!  Thank you for the kind words!

-CorpNewt
