### ISSUE TITLE
Microsoft Defender detects as trojan

### ISSUE THREAD

**Issue by JJTech0130** [corpnewt/ProperTree#97]
https://www.virustotal.com/gui/file/85ecc83df6a8c044e82dcd52d9203a87d3e0d06230d5faa89ab35f895078cc61/detection
Commit from today did it, old versions not detected. Does it on my local machine too.

**Comment by corpnewt** [comment]
Huh - that's... weird.  The only thing I did was update the menu.plist - the changes there should not cause any issues (you can check them for yourself).  It's a false positive for sure, but I'm not sure why it triggers.

-CorpNewt

**Comment by JJTech0130** [comment]
Well, it seems to have been a bug in their system. Rescanned the *same file* today and Microsoft thinks it's clean (even on VirusTotal). Weird.
